// Synopsis per project, per locale.
export const synopses = {
  'the-last-lap': {
    en: `"The Last Lap" is a thrilling documentary series that delves into the racing career of Carlos Alberto "Lole" Reutemann, one of the most celebrated racing drivers of the 70s and 80s. The doc-series covers Reutemann's beginnings in motorsport through his rise as a legend in the highest category, with a particular focus on the dramatic and tense 1981 Formula One World Championship season. The series unveils the intense rivalry, controversies, and alleged conspiracies that surrounded Reutemann during his fight for the title that year, as well as everything that being a Formula One driver entailed, particularly in those golden years when the category went through its most dangerous decade.`,
    es: `«The Last Lap» es una apasionante serie documental que se adentra en la carrera deportiva de Carlos Alberto «Lole» Reutemann, uno de los pilotos más célebres de los años setenta y ochenta. La serie recorre los inicios de Reutemann en el automovilismo hasta su consagración como leyenda en la categoría reina, con especial atención a la dramática y tensa temporada del Campeonato del Mundo de Fórmula 1 de 1981. Revela la intensa rivalidad, las polémicas y las supuestas conspiraciones que rodearon a Reutemann en su lucha por el título aquel año, así como todo lo que suponía ser piloto de Fórmula 1, sobre todo en aquellos años dorados en que la categoría atravesó su década más peligrosa.`,
  },
  'las-heras': {
    en: `A woman who barely remembers her father travels from Madrid to a town in the Argentine Pampas to sell an inheritance. The process drags on, and while she waits, the landscape, the bodies, and the stories of others give her back a history that was never hers, but which she begins to inhabit.`,
    es: `Una mujer que apenas recuerda a su padre viaja desde Madrid a un pueblo de la Pampa argentina para vender una herencia. El trámite se dilata y, mientras espera, el paisaje, los cuerpos y las historias ajenas le devuelven una historia que nunca fue suya, pero que empieza a habitar.`,
  },
  'foodball': {
    en: `Foodball is a documentary series that brings together two universal passions: food and football. Led by a charismatic rock musician and lifelong football fanatic, we journey through cities where football is not mere entertainment but the deepest expression of a people's identity — a space that reflects national, class, and religious tensions, and for many, the greatest joy of their week. We visit the most vibrant and meaningful stadiums in Mexico, Colombia, Argentina, Brazil, Spain, Morocco, Portugal, Italy, Turkey, and Greece, discovering how football is eaten, celebrated, and lived in each culture. In each episode, our host explores the city, connects with figures from local food culture, and alongside fans of the most iconic clubs, learns about the history, the traditional cuisine, and the local football scene. The journey ends on match day. More than gastronomy or sport, Foodball is a sensory and human journey — a portrait of the fan, their identity, and their way of understanding life through flavors, stadiums, and streets. Foodball unites the two largest cultural industries on the planet, where people from every corner of the world have found in football a family, and in food a home.`,
    es: `Foodball es una serie documental que reúne dos pasiones universales: la comida y el fútbol. De la mano de un carismático músico de rock y fanático del fútbol de toda la vida, recorremos ciudades donde el fútbol no es mero entretenimiento, sino la expresión más profunda de la identidad de un pueblo: un espacio que refleja tensiones nacionales, de clase y religiosas y, para muchos, la mayor alegría de la semana. Visitamos los estadios más vibrantes y significativos de México, Colombia, Argentina, Brasil, España, Marruecos, Portugal, Italia, Turquía y Grecia, descubriendo cómo se come, se celebra y se vive el fútbol en cada cultura. En cada episodio, nuestro anfitrión explora la ciudad, conecta con figuras de la cultura gastronómica local y, junto a los hinchas de los clubes más icónicos, conoce la historia, la cocina tradicional y el fútbol de cada lugar. El viaje termina el día del partido. Más que gastronomía o deporte, Foodball es un viaje sensorial y humano: un retrato del hincha, de su identidad y de su manera de entender la vida a través de sabores, estadios y calles. Foodball une las dos mayores industrias culturales del planeta, donde personas de cada rincón del mundo han encontrado en el fútbol una familia y en la comida un hogar.`,
  },
  'body-hunters': {
    en: `During the initial phase of a groundbreaking clinical trial—centered around a molecule that could significantly extend human life—catastrophic events begin to unfold, endangering the lives of the young volunteers and threatening the integrity of the experiment. With time running out, the biotech company Life-5 ("body hunters") races to protect the participants and complete the trial, all while uncovering the force behind the sabotage.`,
    es: `Durante la fase inicial de un ensayo clínico pionero —centrado en una molécula capaz de prolongar significativamente la vida humana— empiezan a producirse hechos catastróficos que ponen en peligro la vida de los jóvenes voluntarios y amenazan la integridad del experimento. Contra el reloj, la empresa biotecnológica Life-5 («body hunters») se afana por proteger a los participantes y completar el ensayo, mientras trata de descubrir quién está detrás del sabotaje.`,
  },
  'inner-portrait': {
    en: `Inner Portrait (2025) is a 22-to-30-minute documentary created by Turkish Airlines and media artist Refik Anadol that explores the transformative impact of travel on the human spirit. It follows four individuals traveling abroad for the first time, using AI and biosensing data to transform their emotional, cognitive, and sensory experiences into digital art.`,
    es: `Inner Portrait (2025) es un documental de entre 22 y 30 minutos creado por Turkish Airlines y el artista digital Refik Anadol que explora el impacto transformador de los viajes en el espíritu humano. Sigue a cuatro personas que viajan al extranjero por primera vez y emplea inteligencia artificial y datos biométricos para convertir sus experiencias emocionales, cognitivas y sensoriales en arte digital.`,
  },
  'bionica': {
    en: `Emma, a quadriplegic woman, undergoes an unusual treatment to regain her mobility and also gain other skills. Under the command of Dr. Wuntz, his daughter Ariadna and his disciple Larsen, the Bionica clinic will kill the patient, then cut off her head and place her on a pedestal where she will become conscious while they operate on the body. But Dr. Wuntz has an idea to go further that will go beyond all limits.`,
    es: `Emma, una mujer cuadripléjica, se somete a un tratamiento insólito para recuperar su movilidad y adquirir además otras capacidades. Bajo el mando del doctor Wuntz, su hija Ariadna y su discípulo Larsen, la clínica Bionica matará a la paciente, le cortará la cabeza y la colocará sobre un pedestal, donde recobrará la consciencia mientras operan el cuerpo. Pero el doctor Wuntz tiene una idea para ir más lejos, más allá de todos los límites.`,
  },
  'you-and-everything-else': {
    en: `"Two Women" chronicles the journey of two friends who have an enduring, complicated love-hate relationship. They find their lives intricately linked as they cross each other's paths through various phases in life. Ryu Eun-jung (Kim Go-eun), a charming and honest woman, forms a close bond with Cheon Sang-yeon (Park Ji-hyun), who becomes her best friend and rival. The series explores the intricacies of their complex friendship as they navigate the challenges of life, feeling both care and envy for each other. The story traces their friendship from their school days to their twenties and thirties, showing how their bond changes over time. At 42 years old, they reunite in the face of a profound challenge: Sang-yeon's battle with cancer. The touching narrative delves into their shared past, their separate paths to becoming a screenwriter and a successful film director, and the enduring impact they've had on each other's lives.`,
    es: `«Two Women» narra el recorrido de dos amigas unidas por una relación de amor y odio tan duradera como complicada. Sus vidas quedan íntimamente entrelazadas a medida que sus caminos se cruzan a lo largo de distintas etapas. Ryu Eun-jung (Kim Go-eun), una mujer encantadora y honesta, forja un vínculo estrecho con Cheon Sang-yeon (Park Ji-hyun), que se convierte en su mejor amiga y su rival. La serie explora los entresijos de esa amistad compleja mientras ambas afrontan los desafíos de la vida, sintiendo a la vez cariño y envidia la una por la otra. La historia sigue su amistad desde los años de colegio hasta los veinte y los treinta, mostrando cómo cambia su vínculo con el tiempo. A los 42 años se reencuentran ante una prueba profunda: la batalla de Sang-yeon contra el cáncer. Este relato conmovedor ahonda en su pasado compartido, en sus caminos separados hacia la escritura y la dirección de cine, y en la huella imborrable que dejaron en la vida de la otra.`,
  },
  'villa-malaga': {
    en: `After purchasing some old bottles of Málaga wine at an auction, surprisingly bottled in the Swiss city of Lenzburg at the beginning of the last century, Stefan Persili embarks on a journey through the past and present of Málaga wines. It is a culture deeply rooted in vineyards since ancient times, which has given rise to traditions, shaped landscapes, and left a mark on people's lives, shaping their understanding of life in connection with nature and the vine. Filmed in Switzerland and Málaga, the movie traces the history of wines that once became perhaps the most renowned and prestigious in the world, and now are experiencing a strong resurgence in the hands of innovative winemakers. A historical tasting brings together friends and experts, delving into the lives of different characters: men and women who strive to preserve the viticultural heritage while also embracing new winemaking techniques that are surprising the wine world.`,
    es: `Tras adquirir en una subasta unas viejas botellas de vino de Málaga, sorprendentemente embotelladas en la ciudad suiza de Lenzburg a principios del siglo pasado, Stefan Persili emprende un viaje por el pasado y el presente de los vinos malagueños. Se trata de una cultura profundamente arraigada en los viñedos desde la antigüedad, que ha dado lugar a tradiciones, ha modelado paisajes y ha dejado huella en la vida de las personas, moldeando su manera de entender la existencia en conexión con la naturaleza y la vid. Rodada en Suiza y en Málaga, la película recorre la historia de unos vinos que llegaron a ser quizá los más renombrados y prestigiosos del mundo y que hoy viven un fuerte resurgir de la mano de bodegueros innovadores. Una cata histórica reúne a amigos y expertos y se adentra en la vida de distintos personajes: hombres y mujeres que se esfuerzan por preservar el patrimonio vitivinícola sin renunciar a nuevas técnicas de elaboración que están sorprendiendo al mundo del vino.`,
  },
  'nccr-robotics': {
    en: `The intricate dance between humans and machines, showcasing the remarkable autonomy, adaptability, and resilience of our robotic counterparts. Through the words of five distinguished scientists, we are granted a glimpse into the awe-inspiring potential of robotics — a testament to our indomitable capacity for self-transformation.`,
    es: `La intrincada danza entre humanos y máquinas, que revela la notable autonomía, adaptabilidad y resiliencia de nuestros homólogos robóticos. A través de las palabras de cinco destacados científicos, se nos concede un atisbo del asombroso potencial de la robótica: un testimonio de nuestra indómita capacidad de transformarnos a nosotros mismos.`,
  },
  'el-color-del-cielo': {
    en: `Tristan Del Val and Olivia Bronte meet again by chance in a hotel seventeen years later. At a young age, the philosopher had succumbed to the charm of the celebrity actress. For seventeen years, the memories of their love affair — cut short by her ambitious career plans — had endured. A profound dialogue unfolds between the two: an unvarnished confrontation about success, loss, happiness, and love.`,
    es: `Tristán Del Val y Olivia Bronte se reencuentran por azar en un hotel diecisiete años después. De joven, el filósofo había sucumbido al encanto de la célebre actriz. Durante diecisiete años perduraron los recuerdos de aquel romance, truncado por los ambiciosos planes profesionales de ella. Entre ambos se despliega un diálogo profundo: una confrontación sin adornos sobre el éxito, la pérdida, la felicidad y el amor.`,
  },
  'contigo-capitan': {
    en: `"Contigo Capitán" is a Netflix miniseries (2022) based on true events, which tells the story of the legal battle fought by Peruvian footballer Paolo Guerrero after testing positive in a doping control prior to the 2018 Russia World Cup. The plot follows his struggle to prove his innocence and save his dream of playing in the World Cup.`,
    es: `«Contigo Capitán» es una miniserie de Netflix (2022) basada en hechos reales que narra la batalla legal que libró el futbolista peruano Paolo Guerrero tras dar positivo en un control antidopaje previo al Mundial de Rusia 2018. La trama sigue su lucha por demostrar su inocencia y salvar su sueño de jugar el Mundial.`,
  },
  'larminuta': {
    en: `Summer of 1975. A thirteen-year-old girl becomes, without anyone asking her consent, the "arminuta" (the returned one). That is, she returns to her biological family, of whom she knew nothing. She goes from a comfortable middle-class existence to a life in the Abruzzo countryside, where poverty and lack of education prevail.`,
    es: `Verano de 1975. Una niña de trece años se convierte, sin que nadie le pida su consentimiento, en la «arminuta» (la que regresa). Es decir, vuelve con su familia biológica, de la que no sabía nada. Pasa de una cómoda existencia de clase media a la vida en el campo de los Abruzos, donde imperan la pobreza y la falta de educación.`,
  },
  'singularity': {
    en: `In 2020, Elias van Dorne (John Cusack), CEO of the world's largest manufacturer of robots, will present his most powerful invention to date: Kronos, a super-computer that is supposed to mean the end of all wars. But when Kronos goes online, it doesn't take long for him to realize that the only enemy of the world-friend is man himself – and the computer launches a global robot attack to free the earth from the infection of mankind. 97 years later, only a small number of humans have survived, hiding day in day out from the killer machines. But the two teenagers Andrew (Julian Schaffner) and Calia (Jeannine Wacker) join forces to advance into an unknown world where it is said that there are no robots. They set off on an arduous and dangerous journey – but is their new homeland there at all?`,
    es: `En 2020, Elias van Dorne (John Cusack), director ejecutivo del mayor fabricante de robots del mundo, presenta su invención más poderosa hasta la fecha: Kronos, un supercomputador que promete el fin de todas las guerras. Pero cuando Kronos se pone en marcha, no tarda en concluir que el único enemigo del amigo de la humanidad es el propio ser humano, y desata un ataque robótico global para librar a la Tierra de la infección de la humanidad. Noventa y siete años después, solo un puñado de personas ha sobrevivido, ocultándose día tras día de las máquinas asesinas. Los adolescentes Andrew (Julian Schaffner) y Calia (Jeannine Wacker) unen fuerzas para adentrarse en un mundo desconocido donde, según dicen, no hay robots. Emprenden un viaje arduo y peligroso, pero ¿existe realmente ese nuevo hogar?`,
  },
  'himmelfahrtskommando': {
    en: `A black comedy about the fictional village of Gottlingen, which one day welcomes a very special group of new residents: Nine women and men from an American sect settle in the remote community. When the cult members are killed in an accident, they leave a lot of money behind. The villagers take the dough and remove the traces of the accident. When more cult members from America announce their arrival, the parish council tries to cover up the whole matter. With this fraud, however, the Gottlingers set off a real chain reaction with dramatic consequences - and not only for the masterminds of the plot.`,
    es: `Una comedia negra sobre el pueblo ficticio de Gottlingen, que un día recibe a un grupo muy particular de nuevos vecinos: nueve mujeres y hombres de una secta estadounidense se instalan en la remota comunidad. Cuando los miembros de la secta mueren en un accidente, dejan tras de sí una gran suma de dinero. Los aldeanos se quedan con el botín y borran las huellas del accidente. Cuando más adeptos anuncian su llegada desde América, el consejo parroquial intenta encubrirlo todo. Con este fraude, sin embargo, los de Gottlingen desatan una auténtica reacción en cadena de consecuencias dramáticas, y no solo para los cerebros del plan.`,
  },
};
